# Site settings
title: Рыжий Гид в Стокгольме!
description: Экскурсии и впечатления
keywords: стокгольм, рыжий гид, экскурсия, гид, гид швеция, прогулки
author: stockholm_red
baseurl: ""
url: "https://stockholm.red"

request:
  question: Интересует экскурсия?
  action: Напишите Рыжему Гиду прямо сейчас!

links:
  instagram: https://www.instagram.com/stockholm_red/
  facebook: https://www.facebook.com/foxy.guide/
  telegram: https://t.me/Stockholm_red
  whatsapp: https://wa.me/46739291819

theme: jekyll-theme-cayman